version: "3.8"

services:
  web:
    build: ${PATH_MICROSERVICE}
    container_name: "go-fiber-learn"
    env_file:
      - ${PATH_MICROSERVICE}/.env
    ports:
      - "3000:3000"
    volumes:
      - ${PATH_MICROSERVICE}:/application